package org.evosuite.samples;

/*
 * This file was automatically generated by EvoSuite
 * Tue May 27 14:12:56 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BankAccountManager_ESTest extends BankAccountManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("U&4T}", "U&4T}", 1857.942);
      bankAccountManager0.withdraw("U&4T}", 1.0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.transfer("K~2\"mH6'#C=jqwAwd", "ZB?X*x8Ik[OoPqv", 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid transfer
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.withdraw("", 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Withdrawal must be positive
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.deposit("RIh#w.1sV;L`S*nBB;)", 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Deposit must be positive
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("4T", "4T", 785.163717);
      bankAccountManager0.deposit("4T", 785.163717);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("EF4$a", "D@\"39o}PA>;h", 1.0);
      double double0 = bankAccountManager0.getBalance("EF4$a");
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.transfer((String) null, (String) null, 3733.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("YxsIc=/;{z\"r", "YxsIc=/;{z\"r", 3442.158826451983);
      bankAccountManager0.withdraw("YxsIc=/;{z\"r", 3442.158826451983);
      bankAccountManager0.createAccount("]SJ,;|i|x#", "]SJ,;|i|x#", 3442.158826451983);
      // Undeclared exception!
      try { 
        bankAccountManager0.transfer("YxsIc=/;{z\"r", "]SJ,;|i|x#", 3442.158826451983);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Insufficient funds
         //
         //verifyException("BankAccountManager$BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("9?", "9?", 67.04793);
      // Undeclared exception!
      try { 
        bankAccountManager0.withdraw("9?", 104.445229);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Insufficient funds
         //
         //verifyException("BankAccountManager$BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("Amount must be positive", "Amount must be positive", 0.0378);
      bankAccountManager0.createAccount("]SJ,;N|B|\"#", "]SJ,;N|B|\"#", 0.0378);
      bankAccountManager0.transfer("Amount must be positive", "]SJ,;N|B|\"#", 0.0378);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("axlJsI#c=/o@z&r", "axlJsI#c=/o@z&r", 0.0378);
      bankAccountManager0.createAccount("]SJ,;|B|x#", "]SJ,;|B|x#", 0.0378);
      bankAccountManager0.transfer("axlJsI#c=/o@z&r", "]SJ,;|B|x#", 0.0378);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.transfer("W*Ad29", "Cy[OVv}X1U*]m\"?D  ", 3392.8);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Account not found
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.transfer("", "", 2098.1445873);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid transfer
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.transfer("gzFbT1OBj*KOgAOee|", "gzFbT1OBj*KOgAOee|", (-672.5533947));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid transfer
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.withdraw("", (-1736.988986));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Withdrawal must be positive
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.withdraw("!4Dz%Ki1|j7ma)h'", 2376.6206013533683);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Account not found
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.deposit("D~0R6B'5", (-253.66685703543968));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Deposit must be positive
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.deposit("", 5167.1762440961);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Account not found
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("U4T}", "U4T}", 1869.2980870234003);
      // Undeclared exception!
      try { 
        bankAccountManager0.createAccount("U4T}", "U4T}", 1869.2980870234003);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Account already exists
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.createAccount("K", "K", (-1558.8257229));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid account details
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.createAccount("", "", 2379.186385216382);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid account details
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        //bankAccountManager0.createAccount((String) null, (String) null, 1.0);
        //fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid account details
         //
         //verifyException("BankAccountManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      bankAccountManager0.createAccount("K", "K", 0.0);
      double double0 = bankAccountManager0.getBalance("K");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BankAccountManager bankAccountManager0 = new BankAccountManager();
      // Undeclared exception!
      try { 
        bankAccountManager0.getBalance("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Account not found
         //
         //verifyException("BankAccountManager", e);
      }
  }
}
