package org.evosuite.samples;

/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 19 15:10:50 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvoComplex_ESTest extends EvoComplex_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Double double0 = new Double(1000000.0);
      evoComplex0.ingest("", double0, (Long) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex((-1917), "Lbwl -,RM5e@&Q");
      Double double0 = new Double((-1917));
      Long long0 = new Long(1656678669230830295L);
      evoComplex0.ingest((String) null, double0, long0);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("");
      linkedHashSet0.add("User=<anon> phase=NONE mode=MEAN decay=0.960 window=8 score=0.000 | no-data");
      List<String> list0 = evoComplex0.recommend(linkedHashSet0, (-1917));
      assertTrue(list0.contains("User=<anon> phase=NONE mode=MEAN decay=0.960 window=8 score=0.000 | no-data"));
      assertFalse(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, String> map0 = evoComplex0.configure("F;K+Y04E;=/eS|TX 8@");
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex(1, (String) null);
      Double double0 = new Double(1);
      Long long0 = new Long(1);
      evoComplex0.ingest((String) null, double0, long0);
      Double double1 = new Double(0.75);
      evoComplex0.ingest((String) null, double1, long0);
      String string0 = evoComplex0.explain("");
      assertEquals("User=<anon> phase=IDLE mode=MEAN decay=0.960 window=8 score=0.065 | n=2 recentVol=0.185 next\u2248-0.057", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex(1, (String) null);
      Double double0 = new Double(1);
      Long long0 = new Long(1);
      evoComplex0.ingest((String) null, double0, long0);
      evoComplex0.ingest((String) null, double0, long0);
      evoComplex0.ingest((String) null, double0, long0);
      String string0 = evoComplex0.explain("");
      assertEquals("User=<anon> phase=WARMUP mode=MEAN decay=0.960 window=8 score=0.115 | n=3 recentVol=0.000 next\u22480.115", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      EvoComplex evoComplex1 = new EvoComplex();
      assertFalse(evoComplex1.equals((Object)evoComplex0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex(1, (String) null);
      Double double0 = new Double(1);
      Long long0 = new Long(1);
      evoComplex0.ingest((String) null, double0, long0);
      double double1 = evoComplex0.score("");
      assertEquals(0.038000000000000034, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Double double0 = new Double((-1.0));
      Long long0 = Long.valueOf(3421L);
      evoComplex0.ingest("", double0, long0);
      evoComplex0.ingest("", double0, long0);
      Optional<Double> optional0 = evoComplex0.predictNext((String) null);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex(0, "");
      Double double0 = new Double(0.0);
      Long long0 = new Long(0);
      evoComplex0.ingest("", double0, long0);
      Optional<Double> optional0 = evoComplex0.predictNext("");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex((-815), " | n=");
      Double double0 = new Double((-815));
      Long long0 = Long.valueOf((long) (-815));
      evoComplex0.ingest("", double0, long0);
      double double1 = evoComplex0.score((String) null);
      assertEquals((-31.94800000000003), double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex((-815), " | n=");
      evoComplex0.score((String) null);
      double double0 = evoComplex0.score("");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex((-815), "wU=Y/G'Tm]V,2@d.@");
      evoComplex0.explain(" C#rcetVo");
      evoComplex0.explain("k");
      evoComplex0.score("User= C#rcetVo phase=NONE mode=MEAN decay=0.960 window=8 score=0.000 | no-data");
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("lt");
      linkedHashSet0.add("User=k phase=NONE mode=MEAN decay=0.960 window=8 score=0.000 | no-data");
      linkedHashSet0.add("wU=Y/G'Tm]V,2@d.@");
      linkedHashSet0.add("RY/Ru_B(4");
      linkedHashSet0.add("-FI~-MR CaeE(!Wb4");
      evoComplex0.explain("L \"wI");
      linkedHashSet0.add("H2uH`]");
      evoComplex0.score("[f-XLsnw_80");
      linkedHashSet0.add("vdY e.GvUd");
      linkedHashSet0.add("n&(k");
      linkedHashSet0.add("EvoComplex$ScoreCache");
      linkedHashSet0.add("EPrAJ541qRQ%GKD:^*3");
      linkedHashSet0.add("");
      evoComplex0.score("User=L \"wI phase=NONE mode=MEAN decay=0.960 window=8 score=0.000 | no-data");
      List<String> list0 = evoComplex0.recommend(linkedHashSet0, (-815));
      assertFalse(list0.contains("wU=Y/G'Tm]V,2@d.@"));
      assertTrue(list0.contains("n&(k"));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double((-1336));
      linkedList0.add(double0);
      linkedList0.add(double0);
      Long long0 = new Long((-1712L));
      evoComplex0.ingest((String) null, double0, long0);
      linkedList0.add(double0);
      evoComplex0.ingest((String) null, double0, long0);
      linkedList0.offerLast(double0);
      linkedList0.add(double0);
      linkedList0.addLast(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      evoComplex0.ingest((String) null, double0, long0);
      evoComplex0.ingest((String) null, double0, long0);
      linkedList0.add(double0);
      linkedList0.offerFirst(double0);
      linkedList0.addFirst(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      evoComplex0.ingest((String) null, double0, long0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      Map<String, Object> map0 = evoComplex0.whatIf((String) null, linkedList0);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      linkedList0.add((Double) null);
      Map<String, Object> map0 = evoComplex0.whatIf(">r", linkedList0);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, Object> map0 = evoComplex0.whatIf(" window=", (List<Double>) null);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("eGxh_7o+T");
      linkedHashSet0.add("Y7~");
      EvoComplex evoComplex0 = new EvoComplex();
      Double double0 = new Double((-2653.3734647));
      Long long0 = new Long(45);
      evoComplex0.ingest("Y7~", double0, long0);
      List<String> list0 = evoComplex0.recommend(linkedHashSet0, 45);
      assertTrue(list0.contains("Y7~"));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      List<String> list0 = evoComplex0.recommend(linkedHashSet0, (-930));
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      List<String> list0 = evoComplex0.recommend((Set<String>) null, (-19));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, String> map0 = evoComplex0.configure(" decay=");
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, String> map0 = evoComplex0.configure(" mode=");
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, String> map0 = evoComplex0.configure(" window=");
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, String> map0 = evoComplex0.configure((String) null);
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Optional<Double> optional0 = evoComplex0.predictNext("gpFg");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Double double0 = new Double(1.0E12);
      evoComplex0.ingest("", double0, (Long) null);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Double double0 = new Double((-4));
      EvoComplex evoComplex0 = new EvoComplex();
      Long long0 = new Long((-4));
      evoComplex0.ingest((String) null, double0, long0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      EvoComplex evoComplex0 = new EvoComplex();
      Map<String, String> map0 = evoComplex0.configure(" decOy=");
      assertTrue(map0.isEmpty());
  }
}