/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 15 17:29:09 GMT 2025
 */
package org.evosuite.samples;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ProvaBanca_ESTest extends ProvaBanca_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
	  
	  double t = (-5.34);
	  int n = (-4);
	  int m = -3;
	  byte b = -5;
      boolean boolean0 = ProvaBanca.isPositive(0.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(2759.746331987481, 173.7128245027026);
      provaBanca0.applyInterest();
      assertEquals(482163.076572506, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(2759.746331987481, 173.7128245027026);
      provaBanca0.withdraw(173.7128245027026);
      assertEquals(2586.0335074847785, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca((-361.89), (-361.89));
      provaBanca0.withdraw(0.0);
      assertEquals((-361.89), provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      provaBanca0.deposit((-981.2682701876737));
      assertEquals(359.8, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      provaBanca0.withdraw(359.8);
      double double0 = provaBanca0.getBalance();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca((-1719.139664495594), (-1719.139664495594));
      double double0 = provaBanca0.getBalance();
      assertEquals((-1719.139664495594), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = ProvaBanca.isPositive(359.8);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = ProvaBanca.isPositive((-1719.139664495594));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      provaBanca0.withdraw(359.8);
      provaBanca0.withdraw(220.82720044121);
      assertEquals(0.0, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      provaBanca0.withdraw((-1.0));
      assertEquals(359.8, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      provaBanca0.deposit(359.8);
      assertEquals(719.6, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      provaBanca0.deposit(0.0);
      assertEquals(359.8, provaBanca0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ProvaBanca provaBanca0 = new ProvaBanca(359.8, (-1.0));
      double double0 = provaBanca0.getBalance();
      assertEquals(359.8, double0, 0.01);
  }
}