package org.evosuite.samples;

/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 16 15:40:09 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Simple_ESTest extends Simple_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.f(5);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Simple simple0 = new Simple();
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      int int0 = simple0.sum(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Simple simple0 = new Simple();
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Integer integer0 = new Integer((-1089));
      linkedList0.add((Number) integer0);
      int int0 = simple0.sum(linkedList0);
      assertEquals((-1089), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.square(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.square((-2904));
      assertEquals(8433216, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.f((-1325400064));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Simple simple0 = new Simple();
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      List<Number> list0 = linkedList0.subList(0, 0);
      Float float0 = new Float((float) 0);
      linkedList0.add((Number) float0);
      // Undeclared exception!
      try { 
        simple0.sum(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
//       verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Simple simple0 = new Simple();
      // Undeclared exception!
      try { 
        simple0.sum((Collection<Number>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
//         verifyException("Simple", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.square(7573504);
      assertEquals((-1325400064), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Simple simple0 = new Simple();
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Long long0 = new Long(7573504);
      linkedList0.add((Number) long0);
      int int0 = simple0.sum(linkedList0);
      assertEquals(7573504, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.f(0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Simple simple0 = new Simple();
      int int0 = simple0.f(7573504);
      assertEquals(15147008, int0);
  }
}

